
version: '3.8'
services:
  booking:
    image: booking:1.0
    container_name: booking-container
    build:
      context: ./booking
      dockerfile: booking.Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
          - dbname=travelnest:travelnest@host.docker.internal

  owner:
    image: owner:1.0
    container_name: owner-container
    build:
      context: ./owner
      dockerfile: owner.Dockerfile
    restart: always
    ports:
      - "8081:8081"
    environment:
      - dbname=travelnest:travelnest@host.docker.internal

  renter:
    image: renter:1.0
    container_name: renter-container
    build:
      context: ./renter
      dockerfile: renter.Dockerfile
    restart: always
    ports:
      - "8082:8082"
    environment:
      - dbname=travelnest:travelnest@host.docker.internal

  property:
    image: property:1.0
    container_name: property-container
    build:
      context: ./property
      dockerfile: property.Dockerfile
    restart: always
    ports:
      - "8083:8083"
    environment:
      - dbname=travelnest:travelnest@host.docker.internal

  payment:
    image: payment:1.0
    container_name: payment-container
    build:
      context: ./payment
      dockerfile: payment.Dockerfile
    restart: always
    ports:
      - "8084:8084"
    environment:
      - dbname=travelnest:travelnest@host.docker.internal

  place_booking:
    image: place_booking:1.0
    container_name: place_booking-container
    build:
      context: ./place_booking
      dockerfile: place_booking.Dockerfile
    restart: always
    ports:
      - "8087:5000"
    depends_on:
      - payment
      - property
      - booking
      - renter
      - owner
    environment:
      # property_URL: http://property:8083/property
      # booking_URL: http://booking:8080/booking
      PYTHONUNBUFFERED: 1

  process_booking:
    image: process_booking:1.0
    container_name: process_booking-container
    build:
      context: ./process_booking
      dockerfile: process_booking.Dockerfile
    restart: always
    ports:
      - "8088:5100"
    depends_on:
      - payment
      - property
      - booking
      - renter
      - owner
    environment:
      # property_URL: http://property:8083/property
      # booking_URL: http://booking:8080/booking
      PYTHONUNBUFFERED: 1

  # filter_property:
  #   image: filter_property:1.0
  #   container_name: filter_property-container
  #   build:
  #     context: ./
  #     dockerfile: ./filter_property/filter_property.Dockerfile
  #   restart: always
  #   ports:
  #     - "8086:8086"
  #   depends_on:
  #     - property
  #     - booking
  #   environment:
  #     property_URL: http://property:8083/property
  #     booking_URL: http://booking:8080/booking
  #     PYTHONUNBUFFERED: 1
